name: Gerar APK Sem Studio v4

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Permite rodar manualmente se precisar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código (Checkout)
      uses: actions/checkout@v4

    - name: Configurar Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Configurar Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.5

    - name: Compilar APK (Debug)
      run: gradle assembleDebug

    - name: Upload do APK
      uses: actions/upload-artifact@v4
      with:
        name: MeuLiveApp
        path: app/build/outputs/apk/debug/app-debug.apk
        compression-level: 0 # Faz o upload mais rápido sem comprimir o que já é zip
